package GUI;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alvaro
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {
    private Controlador c = new Controlador();
    /**
     * Creates new form MenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImg1 = new javax.swing.JLabel();
        EliminarEmpleados = new javax.swing.JButton();
        AñadirEmpleado = new javax.swing.JButton();
        MostrarEmpleados = new javax.swing.JButton();
        GuardarCambios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyEnterpriseController 2.0");
        setMinimumSize(new java.awt.Dimension(436, 311));
        getContentPane().setLayout(null);

        jLabelImg1.setIcon(new javax.swing.ImageIcon("C:\\Users\\alvaro\\Documents\\NetBeansProjects\\GestionDeEmpleados\\src\\img\\empleados.jpg")); // NOI18N
        jLabelImg1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabelImg1.setName(""); // NOI18N
        getContentPane().add(jLabelImg1);
        jLabelImg1.setBounds(120, 10, 180, 150);

        EliminarEmpleados.setText("Eliminar Empleado");
        EliminarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarEmpleados);
        EliminarEmpleados.setBounds(280, 180, 140, 23);

        AñadirEmpleado.setText("Añadir Empleado");
        AñadirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(AñadirEmpleado);
        AñadirEmpleado.setBounds(0, 180, 140, 23);

        MostrarEmpleados.setText("Mostrar Empleados");
        MostrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarEmpleados);
        MostrarEmpleados.setBounds(140, 180, 140, 23);

        GuardarCambios.setText("Guardar Cambios");
        GuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarCambios);
        GuardarCambios.setBounds(140, 210, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BgGreen2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 440, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarEmpleadosActionPerformed
        VistaMostrarEmpleados vme = new VistaMostrarEmpleados(c);
        vme.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MostrarEmpleadosActionPerformed

    private void GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosActionPerformed
       c.guardar();        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarCambiosActionPerformed

    private void AñadirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirEmpleadoActionPerformed
        VistaAñadirEmpleado vap = new VistaAñadirEmpleado();
        vap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AñadirEmpleadoActionPerformed

    private void EliminarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEmpleadosActionPerformed
        VistaEliminarEmpleado vee = new VistaEliminarEmpleado(c);
        vee.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
         Controlador c = new Controlador(); 
         c.cargar();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirEmpleado;
    private javax.swing.JButton EliminarEmpleados;
    private javax.swing.JButton GuardarCambios;
    private javax.swing.JButton MostrarEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImg1;
    // End of variables declaration//GEN-END:variables

  
}
